// Gerado automaticamente a partir de pg_proc (sigav/private), restrito às
// funções que aparecem em rpc-permissions.ts. Não editar à mão.
//
// Determina como o adaptador (src/lib/db/rpc-adapter.ts) precisa desembrulhar
// o resultado de "select * from sigav.fn(...)" para reproduzir o formato que
// o cliente banco-js já entregava via PostgREST:
//   - "set":    a função é SETOF/TABLE(...) — data = todas as linhas (array).
//   - "scalar": a função devolve um valor único (jsonb/boolean/uuid/text/...)
//               — data = o valor da única coluna da única linha, sem array.
//   - "void":   a função não devolve nada — data = null.

export type RpcReturnShape = "set" | "scalar" | "void";

export const RPC_RETURN_SHAPE: Readonly<Record<string, RpcReturnShape>> = {
  "FC_INCLUIR_PESSOA_EQUIPE": "scalar",
  "FC_INCLUIR_PERGUNTA": "scalar",
  "FC_INCLUIR_SECAO": "scalar",
  "FC_CICLO_ACEITA_RESPOSTA": "scalar",
  "FC_ATRIB_TODOS_DISPONIVEIS": "scalar",
  "FC_ATRIB_PARTICIPANTE": "scalar",
  "FC_ATRIB_PARTICIPANTE_LOTE": "scalar",
  "FC_PODE_ACESSAR_CICLO": "scalar",
  "FC_PODE_AUDITAR": "scalar",
  "FC_PODE_EDITAR_SUBMISSAO": "scalar",
  "FC_PODE_GERIR_PESQUISA": "scalar",
  "FC_PODE_REGISTRAR_PRESENCA": "scalar",
  "FC_PODE_VER_PRESENCA": "scalar",
  "FC_REIVINDICAR_ACESSO": "set",
  "FC_CRIAR_E_ATRIB_PARTIC": "scalar",
  "FC_CRIAR_RASCUNHO_PESQUISA": "scalar",
  "FC_PESSOA_SESSAO": "scalar",
  "FC_EXCLUIR_PERGUNTA": "scalar",
  "FC_DUPLICAR_ITEM_CONSTRUTOR": "scalar",
  "FC_AGENDAR_ENVIO_MANUAL": "scalar",
  "FC_APLICAR_PUBLICO_AVALIACAO": "scalar",
  "FC_ARQ_GRAVAR": "scalar",
  "FC_ARQ_LISTAR": "set",
  "FC_ARQ_OBTER": "set",
  "FC_ARQ_REMOVER": "scalar",
  "FC_ATUALIZAR_MARCA_PLATAFORMA": "scalar",
  "FC_BUSCAR_PESSOAS_PUBLICO": "scalar",
  "FC_CLONAR_PESQUISA": "scalar",
  "FC_CONCLUIR_EMAIL_PARTICIPANTE": "void",
  "FC_CRIAR_NOVA_VERSAO_PESQUISA": "scalar",
  "FC_DEFINIR_COMUNICADO_INICIO": "scalar",
  "FC_DEFINIR_COR_BARRA_LATERAL": "scalar",
  "FC_DEFINIR_COR_PAINEL_ACESSO": "scalar",
  "FC_DEFINIR_FUNDO_ACESSO": "scalar",
  "FC_DEFINIR_MODELO_AVALIACAO": "scalar",
  "FC_DEFINIR_NOTIFICACAO_EMAIL": "scalar",
  "FC_DEFINIR_PERMISSOES_PESSOA": "scalar",
  "FC_DEFINIR_PRESENCA_PLATAFORMA": "scalar",
  "FC_DEFINIR_RETENCAO_ANONIMA": "scalar",
  "FC_DEFINIR_TEXTOS_EMAIL": "scalar",
  "FC_DEFINIR_TEXTOS_MARCA": "scalar",
  "FC_EXCLUIR_PESQUISA_ARQUIVADA": "scalar",
  "FC_EXCLUIR_PESQUISA_RASCUNHO": "scalar",
  "FC_EXCLUIR_REGRA_CONDICIONAL": "scalar",
  "FC_LISTAR_ACESSOS_PAGINADOS": "scalar",
  "FC_LISTAR_AUDIENCIA_EMAIL": "scalar",
  "FC_LISTAR_AUDITORIA_PESSOA": "scalar",
  "FC_LISTAR_CICLOS_LIDERANCA": "scalar",
  "FC_LISTAR_CICLOS_LIDERANCA_ADM": "scalar",
  "FC_LISTAR_CICLOS_PESQUISA": "scalar",
  "FC_LISTAR_DIMENSOES_PUBLICO": "scalar",
  "FC_LISTAR_ENVIOS_EMAIL": "scalar",
  "FC_LISTAR_MODELOS_AVALIACAO": "scalar",
  "FC_LISTAR_PESQUISAS_ARQ": "scalar",
  "FC_LISTAR_PESSOAS_SEM_CHEFIA": "scalar",
  "FC_LISTAR_PRESENCA_ONLINE": "scalar",
  "FC_LISTAR_REGRAS_CONDICIONAIS": "scalar",
  "FC_LISTAR_RESPOSTAS_CICLO": "scalar",
  "FC_OBTER_CICLO_CDDI_VIGENTE": "scalar",
  "FC_OBTER_CONTEXTO_PLATAFORMA": "scalar",
  "FC_OBTER_FORMULARIO_PUBLICO": "scalar",
  "FC_OBTER_MARCA_PLATAFORMA": "scalar",
  "FC_OBTER_MARCA_PUBLICA": "scalar",
  "FC_OBTER_MINHA_EQUIPE": "scalar",
  "FC_OBTER_PAINEL_PESQUISA": "scalar",
  "FC_OBTER_REGRAS_DO_CICLO": "scalar",
  "FC_ORIGENS_DA_REGRA": "set",
  "FC_PESQUISAR_EQUIPE": "scalar",
  "FC_PESQUISAR_PESSOA_ADMIN": "scalar",
  "FC_PREVISUALIZAR_PUBLICO": "scalar",
  "FC_REGISTRAR_PRESENCA": "scalar",
  "FC_REGRA_GERA_CICLO": "scalar",
  "FC_REIVINDICAR_EMAILS": "scalar",
  "FC_REMOVER_RESPOSTA_PESSOA": "scalar",
  "FC_SALVAR_REGRA_CONDICIONAL": "scalar",
  "FC_SRV_CONCLUIR_EMAIL": "void",
  "FC_SRV_CONSUMIR_LIMITE_PUBLICO": "scalar",
  "FC_SRV_ENVIAR_RESP_ANON": "scalar",
  "FC_SRV_EXPIRAR_RASCUNHOS_ANON": "scalar",
  "FC_SRV_GRAVAR_RESP_ANON": "scalar",
  "FC_SRV_INICIAR_RESP_ANON": "scalar",
  "FC_SRV_OBTER_FORM_ANONIMO": "scalar",
  "FC_SRV_REGISTRAR_ERRO": "void",
  "FC_SRV_REGISTRAR_TRANSPORTE": "scalar",
  "FC_SRV_RESOLVER_IDENT_OAUTH": "scalar",
  "FC_SRV_REIVINDICAR_EMAILS": "scalar",
  "FC_SRV_VERIFICAR_CONTRATO_RPC": "scalar",
  "FC_SRV_VERIFICAR_MIGRATIONS": "scalar",
  "FC_RESUMO_BASE_PESSOAS": "scalar",
  "FC_OBTER_VISUAL_CICLO": "scalar",
  "FC_PAINEL_MONITOR_CDDI": "scalar",
  "FC_OBTER_CONTEXTO_CDDI": "scalar",
  "FC_OBTER_IDENTIDADE_CDDI": "scalar",
  "FC_OBTER_ESPACO_EQUIPE": "scalar",
  "FC_SAUDE_PLATAFORMA": "scalar",
  "FC_OBTER_CONSTRUTOR": "scalar",
  "FC_OBTER_PAINEL_PESQ": "scalar",
  "FC_OBTER_OPERACOES_PESQUISA": "scalar",
  "FC_TEM_PAPEL_ATIVO": "scalar",
  "FC_TEM_MODULO": "scalar",
  "FC_EMAIL_INSTITUC_PERMITIDO": "scalar",
  "FC_E_ADMINISTRADOR": "scalar",
  "FC_LISTAR_PARTIC_CICLO": "scalar",
  "FC_LISTAR_CICLOS_PARTIC": "scalar",
  "FC_LISTAR_PESQUISAS_GERIDAS": "scalar",
  "FC_LISTAR_CATALOGO_PESQUISA": "scalar",
  "FC_LISTAR_VINCULOS_LIDERANCA": "scalar",
  "FC_GERIR_CICLO_PESQUISA": "scalar",
  "FC_MOVER_PERGUNTA_SECAO": "scalar",
  "FC_REMOVER_PESSOA_EQUIPE": "scalar",
  "FC_REORDENAR_ITEM_CONSTRUTOR": "scalar",
  "FC_RESOLVER_PESSOA_AUTENTIC": "scalar",
  "FC_SALVAR_RESPOSTA_CDDI": "scalar",
  "FC_SALVAR_RESPOSTA_PESQUISA": "scalar",
  "FC_BUSCAR_PESSOAS_CICLO": "scalar",
  "FC_BUSCAR_CANDIDATOS_EQUIPE": "scalar",
  "FC_DEFINIR_SITUACAO_PARTIC": "scalar",
  "FC_DEFINIR_AVATAR": "scalar",
  "FC_DEFINIR_VINCULO_LIDERANCA": "scalar",
  "FC_INICIAR_OU_RETOMAR_CDDI": "scalar",
  "FC_INICIAR_OU_RETOMAR_SUBM": "scalar",
  "FC_INICIAR_OU_RETOMAR_PESQ": "scalar",
  "FC_ENVIAR_SUBMISSAO_CDDI": "scalar",
  "FC_ENVIAR_SUBMISSAO_PESQUISA": "scalar",
  "FC_SINCR_LINHAS_GESTOR_CDDI": "scalar",
  "FC_SINCR_AVATAR_GOOGLE": "scalar",
  "FC_SINCR_LINHAS_BASE_PESSOA": "scalar",
  "FC_SEM_ACENTO_MINUSCULA": "scalar",
  "FC_ATUALIZAR_VISUAL_CICLO": "scalar",
  "FC_ATUALIZAR_PESSOA_ADMIN": "scalar",
  "FC_ATUALIZAR_PERGUNTA": "scalar",
  "FC_ATUALIZAR_SECAO": "scalar",
};
