// Gerado automaticamente: replay cronológico de TODOS os GRANT/REVOKE das 192
// migrations do projeto Supabase original, cruzado contra o catálogo real do
// banco (sigav/private). Não editar à mão — regenerar quando permissões mudarem.
//
// Substitui, em nível de aplicação, a distinção anon/authenticated/service_role
// que antes o PostgREST fazia via roles do Postgres. Como db_dataware usa uma
// única credencial de conexão (usr_sip_app, sem CREATEROLE), esta tabela é a
// ÚNICA linha de defesa que impede uma sessão autenticada comum de invocar uma
// função pensada para cron/serviço (ex.: fc_srv_reivindicar_emails) ou uma
// sessão anônima de invocar uma RPC administrativa.
//
// Duas classes de função ficam DE FORA de propósito:
//   - as que nunca aparecem num GRANT (triggers como validate_cddi_submission,
//     set_updated_at: o Postgres as chama internamente, nunca via API);
//   - as que o histórico revoga de todos (ex.: fc_abrir_ciclos_agendados, que
//     por decisão de projeto só é chamada de dentro de outra security definer).
//
// Exceção: "fc_srv_registrar_erro_aplicacao" é acrescentada pelo gerador — é
// função nova (scripts/bootstrap-db-dataware-usuario-unico.sql), fora do
// histórico de migrations.

export type RpcRole = "anon" | "authenticated" | "service_role";

export const RPC_PERMISSIONS: Readonly<Record<string, readonly RpcRole[]>> = {
  "add_person_to_my_team": ["authenticated"],
  "add_survey_question": ["authenticated"],
  "add_survey_section": ["authenticated"],
  "application_accepts_responses": ["authenticated"],
  "assign_admin_all_available_participants": ["authenticated"],
  "assign_admin_application_participant": ["authenticated"],
  "assign_admin_application_participants_bulk": ["authenticated"],
  "can_access_application": ["authenticated"],
  "can_audit_platform": ["authenticated"],
  "can_edit_submission": ["authenticated"],
  "can_manage_surveys": ["authenticated"],
  "can_track_platform_presence": ["authenticated"],
  "can_view_platform_presence": ["authenticated"],
  "claim_my_access": ["authenticated"],
  "create_and_assign_admin_participant": ["authenticated"],
  "create_survey_draft": ["authenticated"],
  "current_person_id": ["authenticated"],
  "delete_survey_question": ["authenticated"],
  "duplicate_survey_builder_item": ["authenticated"],
  "fc_agendar_envio_manual": ["authenticated"],
  "fc_atualizar_marca_plataforma": ["authenticated"],
  "fc_clonar_pesquisa": ["authenticated"],
  "fc_concluir_email_participante": ["service_role"],
  "fc_criar_nova_versao_pesquisa": ["authenticated"],
  "fc_definir_cor_barra_lateral": ["authenticated"],
  "fc_definir_cor_painel_acesso": ["authenticated"],
  "fc_definir_fundo_acesso": ["authenticated"],
  "fc_definir_modelo_avaliacao": ["authenticated"],
  "fc_definir_notificacao_email": ["authenticated"],
  "fc_definir_perfil_pessoa": ["authenticated"],
  "fc_definir_presenca_plataforma": ["authenticated"],
  "fc_definir_retencao_anonima": ["authenticated"],
  "fc_definir_textos_email": ["authenticated"],
  "fc_definir_textos_marca": ["authenticated"],
  "fc_excluir_pesquisa_arquivada": ["authenticated"],
  "fc_excluir_pesquisa_rascunho": ["authenticated"],
  "fc_excluir_regra_condicional": ["authenticated"],
  "fc_listar_acessos_paginados": ["authenticated"],
  "fc_listar_audiencia_email": ["authenticated"],
  "fc_listar_auditoria_pessoa": ["authenticated"],
  "fc_listar_ciclos_lideranca": ["authenticated"],
  "fc_listar_ciclos_lideranca_adm": ["authenticated"],
  "fc_listar_ciclos_pesquisa": ["authenticated"],
  "fc_listar_envios_email": ["authenticated"],
  "fc_listar_modelos_avaliacao": ["authenticated"],
  "fc_listar_pesquisas_arq": ["authenticated"],
  "fc_listar_pessoas_sem_chefia": ["authenticated"],
  "fc_listar_presenca_online": ["authenticated"],
  "fc_listar_regras_condicionais": ["authenticated"],
  "fc_listar_respostas_ciclo": ["authenticated"],
  "fc_obter_ciclo_cddi_vigente": ["authenticated"],
  "fc_obter_contexto_plataforma": ["authenticated"],
  "fc_obter_formulario_publico": ["authenticated"],
  "fc_obter_marca_plataforma": ["authenticated"],
  "fc_obter_marca_publica": ["anon", "authenticated", "service_role"],
  "fc_obter_minha_equipe": ["authenticated"],
  "fc_obter_painel_pesquisa": ["authenticated"],
  "fc_obter_regras_do_ciclo": ["authenticated"],
  "fc_origens_da_regra": ["authenticated"],
  "fc_pesquisar_equipe": ["authenticated"],
  "fc_pesquisar_pessoa_admin": ["authenticated"],
  "fc_registrar_presenca": ["authenticated"],
  "fc_regra_gera_ciclo": ["authenticated"],
  "fc_reivindicar_emails": ["service_role"],
  "fc_remover_resposta_pessoa": ["authenticated"],
  "fc_salvar_regra_condicional": ["authenticated"],
  "fc_srv_concluir_email": ["service_role"],
  "fc_srv_consumir_limite_publico": ["service_role"],
  "fc_srv_enviar_resp_anon": ["service_role"],
  "fc_srv_expirar_rascunhos_anon": ["service_role"],
  "fc_srv_gravar_resp_anon": ["service_role"],
  "fc_srv_iniciar_resp_anon": ["service_role"],
  "fc_srv_obter_form_anonimo": ["service_role"],
  "fc_srv_registrar_erro_aplicacao": ["service_role"],
  "fc_srv_registrar_transporte": ["service_role"],
  "fc_srv_reivindicar_emails": ["service_role"],
  "fc_srv_verificar_contrato_rpc": ["service_role"],
  "fc_srv_verificar_migrations": ["service_role"],
  "get_admin_people_base_summary": ["authenticated"],
  "get_application_visual_settings": ["authenticated"],
  "get_cddi_monitoring_dashboard": ["authenticated"],
  "get_my_cddi_context": ["authenticated"],
  "get_my_cddi_identity": ["authenticated"],
  "get_my_team_workspace": ["authenticated"],
  "get_platform_health": ["authenticated"],
  "get_survey_builder": ["authenticated"],
  "get_survey_dashboard": ["authenticated"],
  "get_survey_operations": ["authenticated"],
  "has_active_role": ["authenticated"],
  "has_platform_module": ["authenticated"],
  "is_allowed_institutional_email": ["authenticated"],
  "is_platform_administrator": ["authenticated"],
  "list_access_workspace": ["authenticated"],
  "list_admin_application_participants": ["authenticated"],
  "list_admin_participant_applications": ["authenticated"],
  "list_managed_surveys": ["authenticated"],
  "list_my_survey_catalog": ["authenticated"],
  "list_platform_admin_leadership_links": ["authenticated"],
  "manage_survey_cycle": ["authenticated"],
  "move_survey_question_to_section": ["authenticated"],
  "remove_person_from_my_team": ["authenticated"],
  "reorder_survey_builder_item": ["authenticated"],
  "resolve_authenticated_person": ["authenticated"],
  "save_my_cddi_answer": ["authenticated"],
  "save_my_survey_answer": ["authenticated"],
  "search_admin_people_for_application": ["authenticated"],
  "search_team_candidates": ["authenticated"],
  "set_admin_application_participant_status": ["authenticated"],
  "set_my_avatar_choice": ["authenticated"],
  "set_my_avatar_url": ["authenticated"],
  "set_person_role": ["authenticated"],
  "set_platform_admin_leadership_link": ["authenticated"],
  "start_or_resume_my_cddi_submission": ["authenticated"],
  "start_or_resume_my_submission": ["authenticated"],
  "start_or_resume_my_survey_submission": ["authenticated"],
  "submit_my_cddi_submission": ["authenticated"],
  "submit_my_survey_submission": ["authenticated"],
  "sync_cddi_manager_rows": ["service_role"],
  "sync_my_google_avatar": ["authenticated"],
  "sync_people_base_rows": ["service_role"],
  "unaccent_lower": ["authenticated"],
  "update_application_visual_settings": ["authenticated"],
  "update_platform_admin_person": ["authenticated"],
  "update_survey_question": ["authenticated"],
  "update_survey_section": ["authenticated"],
};

export function isRpcAllowedForRole(functionName: string, role: RpcRole): boolean {
  const roles = RPC_PERMISSIONS[functionName];
  return Boolean(roles && roles.includes(role));
}
