// Gerado automaticamente a partir de pg_proc (sigav/private), restrito às
// funções que aparecem em rpc-permissions.ts. Não editar à mão.
//
// Determina como o adaptador (src/lib/db/rpc-adapter.ts) precisa desembrulhar
// o resultado de "select * from sigav.fn(...)" para reproduzir o formato que
// o cliente supabase-js já entregava via PostgREST:
//   - "set":    a função é SETOF/TABLE(...) — data = todas as linhas (array).
//   - "scalar": a função devolve um valor único (jsonb/boolean/uuid/text/...)
//               — data = o valor da única coluna da única linha, sem array.
//   - "void":   a função não devolve nada — data = null.

export type RpcReturnShape = "set" | "scalar" | "void";

export const RPC_RETURN_SHAPE: Readonly<Record<string, RpcReturnShape>> = {
  "add_person_to_my_team": "scalar",
  "add_survey_question": "scalar",
  "add_survey_section": "scalar",
  "application_accepts_responses": "scalar",
  "assign_admin_all_available_participants": "scalar",
  "assign_admin_application_participant": "scalar",
  "assign_admin_application_participants_bulk": "scalar",
  "can_access_application": "scalar",
  "can_audit_platform": "scalar",
  "can_edit_submission": "scalar",
  "can_manage_surveys": "scalar",
  "can_track_platform_presence": "scalar",
  "can_view_platform_presence": "scalar",
  "claim_my_access": "set",
  "create_and_assign_admin_participant": "scalar",
  "create_survey_draft": "scalar",
  "current_person_id": "scalar",
  "delete_survey_question": "scalar",
  "duplicate_survey_builder_item": "scalar",
  "fc_agendar_envio_manual": "scalar",
  "fc_atualizar_marca_plataforma": "scalar",
  "fc_clonar_pesquisa": "scalar",
  "fc_concluir_email_participante": "void",
  "fc_criar_nova_versao_pesquisa": "scalar",
  "fc_definir_cor_barra_lateral": "scalar",
  "fc_definir_cor_painel_acesso": "scalar",
  "fc_definir_fundo_acesso": "scalar",
  "fc_definir_modelo_avaliacao": "scalar",
  "fc_definir_notificacao_email": "scalar",
  "fc_definir_perfil_pessoa": "scalar",
  "fc_definir_presenca_plataforma": "scalar",
  "fc_definir_retencao_anonima": "scalar",
  "fc_definir_textos_email": "scalar",
  "fc_definir_textos_marca": "scalar",
  "fc_excluir_pesquisa_arquivada": "scalar",
  "fc_excluir_pesquisa_rascunho": "scalar",
  "fc_excluir_regra_condicional": "scalar",
  "fc_listar_acessos_paginados": "scalar",
  "fc_listar_audiencia_email": "scalar",
  "fc_listar_auditoria_pessoa": "scalar",
  "fc_listar_ciclos_lideranca": "scalar",
  "fc_listar_ciclos_lideranca_adm": "scalar",
  "fc_listar_ciclos_pesquisa": "scalar",
  "fc_listar_envios_email": "scalar",
  "fc_listar_modelos_avaliacao": "scalar",
  "fc_listar_pesquisas_arq": "scalar",
  "fc_listar_pessoas_sem_chefia": "scalar",
  "fc_listar_presenca_online": "scalar",
  "fc_listar_regras_condicionais": "scalar",
  "fc_listar_respostas_ciclo": "scalar",
  "fc_obter_ciclo_cddi_vigente": "scalar",
  "fc_obter_contexto_plataforma": "scalar",
  "fc_obter_formulario_publico": "scalar",
  "fc_obter_marca_plataforma": "scalar",
  "fc_obter_marca_publica": "scalar",
  "fc_obter_minha_equipe": "scalar",
  "fc_obter_painel_pesquisa": "scalar",
  "fc_obter_regras_do_ciclo": "scalar",
  "fc_origens_da_regra": "set",
  "fc_pesquisar_equipe": "scalar",
  "fc_pesquisar_pessoa_admin": "scalar",
  "fc_registrar_presenca": "scalar",
  "fc_regra_gera_ciclo": "scalar",
  "fc_reivindicar_emails": "scalar",
  "fc_remover_resposta_pessoa": "scalar",
  "fc_salvar_regra_condicional": "scalar",
  "fc_srv_concluir_email": "void",
  "fc_srv_consumir_limite_publico": "scalar",
  "fc_srv_enviar_resp_anon": "scalar",
  "fc_srv_expirar_rascunhos_anon": "scalar",
  "fc_srv_gravar_resp_anon": "scalar",
  "fc_srv_iniciar_resp_anon": "scalar",
  "fc_srv_obter_form_anonimo": "scalar",
  "fc_srv_registrar_erro_aplicacao": "void",
  "fc_srv_registrar_transporte": "scalar",
  "fc_srv_reivindicar_emails": "scalar",
  "fc_srv_verificar_contrato_rpc": "scalar",
  "fc_srv_verificar_migrations": "scalar",
  "get_admin_people_base_summary": "scalar",
  "get_application_visual_settings": "scalar",
  "get_cddi_monitoring_dashboard": "scalar",
  "get_my_cddi_context": "scalar",
  "get_my_cddi_identity": "scalar",
  "get_my_team_workspace": "scalar",
  "get_platform_health": "scalar",
  "get_survey_builder": "scalar",
  "get_survey_dashboard": "scalar",
  "get_survey_operations": "scalar",
  "has_active_role": "scalar",
  "has_platform_module": "scalar",
  "is_allowed_institutional_email": "scalar",
  "is_platform_administrator": "scalar",
  "list_access_workspace": "scalar",
  "list_admin_application_participants": "scalar",
  "list_admin_participant_applications": "scalar",
  "list_managed_surveys": "scalar",
  "list_my_survey_catalog": "scalar",
  "list_platform_admin_leadership_links": "scalar",
  "manage_survey_cycle": "scalar",
  "move_survey_question_to_section": "scalar",
  "remove_person_from_my_team": "scalar",
  "reorder_survey_builder_item": "scalar",
  "resolve_authenticated_person": "scalar",
  "save_my_cddi_answer": "scalar",
  "save_my_survey_answer": "scalar",
  "search_admin_people_for_application": "scalar",
  "search_team_candidates": "scalar",
  "set_admin_application_participant_status": "scalar",
  "set_my_avatar_choice": "scalar",
  "set_my_avatar_url": "scalar",
  "set_person_role": "scalar",
  "set_platform_admin_leadership_link": "scalar",
  "start_or_resume_my_cddi_submission": "scalar",
  "start_or_resume_my_submission": "scalar",
  "start_or_resume_my_survey_submission": "scalar",
  "submit_my_cddi_submission": "scalar",
  "submit_my_survey_submission": "scalar",
  "sync_cddi_manager_rows": "scalar",
  "sync_my_google_avatar": "scalar",
  "sync_people_base_rows": "scalar",
  "unaccent_lower": "scalar",
  "update_application_visual_settings": "scalar",
  "update_platform_admin_person": "scalar",
  "update_survey_question": "scalar",
  "update_survey_section": "scalar",
};
