"use client";

import Link from "next/link";
import { PlatformShell, PlatformSkeleton } from "@/components/platform-shell";
import { deriveModules, profileLabel, usePlatformContext } from "@/lib/platform-context";

const cards = [
  { href: "/admin/pesquisas", tag: "Configuração", title: "Pesquisas e ciclos", description: "Crie versões, organize seções, defina períodos e publique formulários.", metric: "1 ciclo cadastrado", accent: "border-blue-500" },
  { href: "/admin/participantes", tag: "Público", title: "Participantes", description: "Consulte elegibilidade, perfis, e-mails, unidades e situação de participação.", metric: "Base oficial controlada", accent: "border-emerald-500" },
  { href: "/admin/equipes", tag: "Estrutura", title: "Equipes e lideranças", description: "Gerencie vínculos de avaliação e solicitações de correção organizacional.", metric: "Vínculos auditáveis", accent: "border-amber-500" },
  { href: "/admin/acessos", tag: "Segurança", title: "Acessos e permissões", description: "Controle papéis, módulos e exceções de acesso por pessoa.", metric: "Permissão por perfil", accent: "border-violet-500" },
  { href: "/admin/importacao", tag: "Dados", title: "Importações", description: "Valide planilhas oficiais, trate pendências e acompanhe lotes processados.", metric: "Pré-validação em lotes", accent: "border-cyan-500" },
  { href: "/paineis", tag: "Governança", title: "Indicadores e auditoria", description: "Acompanhe adesão, conclusão, inconsistências e eventos relevantes do sistema.", metric: "Visão gerencial", accent: "border-rose-500" },
];

export default function AdminDashboardPage() {
  const { context, loading, error } = usePlatformContext();
  if (loading) return <PlatformSkeleton title="Carregando administração" />;
  if (!context?.person) return <main className="p-10 text-red-700">{error || "Acesso não identificado."}</main>;
  const modules = deriveModules(context);
  const isAdmin = modules.some((item) => item.startsWith("ADMIN_"));
  if (!isAdmin) return <main className="flex min-h-screen items-center justify-center bg-slate-100 px-6"><section className="max-w-lg rounded-3xl bg-white p-8 shadow-xl"><h1 className="text-3xl font-black text-[#003b70]">Acesso restrito</h1><p className="mt-3 text-slate-600">Seu perfil não possui permissão para acessar a central administrativa.</p><Link href="/area" className="mt-6 inline-flex rounded-xl bg-[#003b70] px-5 py-3 font-black text-white">Voltar ao painel</Link></section></main>;

  const user = { fullName: context.person.fullName, institutionalEmail: context.person.institutionalEmail, employeeNumber: context.person.employeeNumber, profileLabel: profileLabel(context), roles: context.roles, modules };
  return <PlatformShell user={user} eyebrow="Gestão da plataforma" title="Central administrativa" actions={<Link href="/admin/importacao" className="hidden rounded-xl bg-[#003b70] px-4 py-2.5 text-sm font-black text-white md:inline-flex">Nova importação</Link>}>
    <section className="overflow-hidden rounded-[2rem] bg-[radial-gradient(circle_at_82%_20%,rgba(57,214,164,.28),transparent_25%),linear-gradient(120deg,#102c4c,#075ea8)] p-7 text-white shadow-xl sm:p-9">
      <div className="grid gap-7 xl:grid-cols-[1.25fr_.75fr] xl:items-end"><div><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black text-emerald-200">Ambiente de gestão</span><h2 className="mt-6 text-3xl font-black sm:text-4xl">Governança de pesquisas em um só lugar</h2><p className="mt-4 max-w-3xl leading-7 text-blue-100">Configure ciclos, públicos, permissões e importações sem misturar a experiência administrativa com a jornada do participante.</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/15 bg-white/10 p-5"><span className="text-xs text-blue-100">Pesquisa configurada</span><strong className="mt-2 block text-3xl">1</strong><small className="text-blue-100">CDDI 2026</small></div><div className="rounded-2xl border border-white/15 bg-white/10 p-5"><span className="text-xs text-blue-100">Módulos administrativos</span><strong className="mt-2 block text-3xl">{modules.filter((item) => item.startsWith("ADMIN_")).length}</strong><small className="text-blue-100">liberados para você</small></div></div></div>
    </section>

    <section className="mt-7"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#0b8f58]">Operação e governança</p><h2 className="mt-1 text-2xl font-black text-[#003b70]">Módulos administrativos</h2><p className="mt-2 text-slate-600">Acesse somente as áreas habilitadas para seu papel institucional.</p></div><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{cards.filter((card) => card.href !== "/admin/acessos" || modules.includes("ADMIN_ACCESS")).map((card) => <Link href={card.href} key={card.href} className={`group rounded-3xl border-t-4 ${card.accent} bg-white p-6 shadow-sm ring-1 ring-[#d7e5f2] transition hover:-translate-y-1 hover:shadow-xl`}><div className="flex items-center justify-between"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{card.tag}</span><b className="text-xl text-[#0b8f58] transition group-hover:translate-x-1">→</b></div><h3 className="mt-5 text-xl font-black text-[#003b70]">{card.title}</h3><p className="mt-3 min-h-20 leading-7 text-slate-600">{card.description}</p><div className="mt-5 border-t border-slate-100 pt-4 text-xs font-black uppercase tracking-[.1em] text-slate-400">{card.metric}</div></Link>)}</div></section>

    <section className="mt-7 grid gap-5 lg:grid-cols-[1fr_1fr]"><article className="rounded-3xl border border-[#d7e5f2] bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.15em] text-[#0b8f58]">Fluxo recomendado</p><h3 className="mt-1 text-xl font-black text-[#003b70]">Publicação segura de um ciclo</h3><ol className="mt-5 space-y-4 text-sm text-slate-600">{["Configure a pesquisa e revise a versão do formulário.","Importe e valide participantes, e-mails e perfis.","Confirme vínculos de liderança e permissões.","Abra o período e acompanhe adesão nos painéis."].map((item, index) => <li key={item} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-blue-50 font-black text-[#003b70]">{index + 1}</span><span className="pt-1">{item}</span></li>)}</ol></article><article className="rounded-3xl border border-[#d7e5f2] bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.15em] text-[#0b8f58]">Controles</p><h3 className="mt-1 text-xl font-black text-[#003b70]">Princípios da plataforma</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Versionamento","Perguntas e ciclos preservados"],["Rastreabilidade","Lotes e alterações auditáveis"],["Segregação","Permissões por papel e módulo"],["Privacidade","Dados pessoais fora do GitHub"]].map(([title, text]) => <div key={title} className="rounded-2xl bg-slate-50 p-4"><strong className="text-[#003b70]">{title}</strong><p className="mt-1 text-sm text-slate-500">{text}</p></div>)}</div></article></section>
  </PlatformShell>;
}
